Store.Load = "STRUCTURENAMINGPATH/scripts/install.Store";
Store.StringAt.ScriptCommand = "/usr/bin/python ";
Store.At.ScriptCommand.AppendString = Store.At.STRUCTURENAMING.Value;
Store.At.ScriptCommand.AppendString = "/scripts/get_pinnacle_pid.py";
SpawnCommand = Store.At.ScriptCommand.Value;

IF.FileErrorList.HasElements.THEN.FileErrorList.DestroyAllChildren = "";
WindowList.FileErrorHierarchy.Destroy = "";

ExecuteNow = "/tmp/add_structures.Script";
